# Dependabot configuration for Soulink Landing Page
# This is a static HTML site, so minimal dependency management is needed

version: 2
updates:
  # Monitor GitHub Actions for any workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
