name: soulink-landing
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: soulink8/soulink-landing
  name: soulink-landing
  source_dir: /
  build_command: ""
  output_dir: /
